//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Futsal.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLoginAttempt
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public string PasswordHash { get; set; }
        public string IPAddress { get; set; }
        public string Reason { get; set; }
        public Nullable<int> ApplicationId { get; set; }
        public Nullable<System.DateTime> AttemptDateTime { get; set; }
        public bool IsSuccessful { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
